### ISSUE TITLE
Typo!

### ISSUE THREAD

**Issue by KFad11** [learn-co-curriculum/phrg-the-web-is-made-of-strings#2]
Found a word misspelled. Towards the top of the document. "**p**agraph" should be "**p**aragraph". Not sure if the bolding was intentional either. Screenshot attached. 
<img width="693" alt="Screen Shot 2019-03-12 at 9 22 02 AM" src="https://user-images.githubusercontent.com/48073883/54203539-d2013600-44a8-11e9-9379-ace2464f176d.png">

**Comment by KFad11** [comment]
@garettarrowood

**Comment by garettarrowood** [comment]
Fixed in #3 .
